apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # Server name is actually the name of the Service,
  # which is going to be the database server URL
  database_url: mongodb-service
