# Secret must be created BEFORE the Deployment
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
# Remember that storing data in a Secret component doesn't
# automatically make it secure: there are built-in mechanim
# (like encryption) for basic security, which are not
# enabled by default
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
